collectionOutputPath=./collection/live-collection.json

mappingType=json

evidenceFormat=docx

copyTestDataToReports=true

testCaseNameColumn=TestCaseName

testScenarioTypeColumn=Scenario

sslEnabled=false
sslCert=./certs/client-cert.pem
sslKey=./certs/client-key.pem
sslPassphrase=YOUR_SSL_PASSPHRASE_HERE
